### ISSUE TITLE
Requirement gathering for QOS scheduler

### ISSUE THREAD

**Issue by amarsri28** [omec-project/upf#379]
We are trying to implement QOS scheduler module in Bess for better traffic management and other aspects. 
Idea is to get all requirements, have fruitful discussion over that before going for implementation.
Pls list down configuration related, scenarios and other requirements here :

**Comment by amarsri28** [comment]
@thakurajayL
@krsna1729 
@pudelkoM 
@badhrinathpa 
@ccascone 
@cmaciocco

**Comment by ccascone** [comment]
Here are some notes I have for Aether 2.0. Please let me know what you think.

- An edge site has multiple slices
- Each slice is realized with a dedicated UPF (bess-upf in our case)
- To guarantee isolation between slices, each UPF is rate limited (per-slice MBR)
- Each session (UE) is rate limited (per-session MBR)
- Each session can have flows (PDRs) for multiple applications
- An application flow can be GBR or non-GBR
- GBR flows have MBR == GBR, we do not support MBR != GBR
- Non-GBR flows can have MBR >= 0
- GBR flows can be delay-critical or regular
- An admission control process (outside the UPF) makes sure that sum of all GBRs < per-slice MBR
- There are two congestion scenarios that we need to handle with QoS
  - TX congestion: when packets queue up inside the bess pipeline, i.e. when ingress bit rate > per-slice MBR
  - RX congestion: when packets queue up at the NIC RX queue, i.e. when ingress packet rate > max BESS packet rate (depend on num workers)
- During congestion the UPF should:
  - Give the highest priority to Delay-Critical GBR packets (to guarantee the lowest latency)
  - Then give priority to regular GBR packets (to guarantee preferential access to available slice bandwidth)
  - Lowest priority goes to non-GBR packets
  - 3GPP defines many priority levels in 5QI, but I think it's ok to start just with the above 3 levels (Delay-Critical GBR, GBR, non-GBR) 
- If it is necessary to drop packets to conform to per-slice MBR
  - Only non-GBR packets can be dropped
  - Dropping should be done fairly between UEs and between application flows, i.e.:
    - Bandwidth not used for GBR flows should be distributed equally to all UEs
    - Available per-UE bandwidth should be distributed equally to all non-GBR flows of the same UE

**Comment by ccascone** [comment]
@amarsri28 any feedback on this?
