### ISSUE TITLE
Maximum value of PDR/QER/FAR table size?

### ISSUE THREAD

**Issue by ParkGyuhwan** [omec-project/upf#448]
Is there a limit to the size of the PDR/QER/FAR table?
I tried to test a large number of rules by setting each table size 10 times the default value.
```
    "table_sizes": {
        "": "Example sizes based on sim mode and 50K sessions. Customize as per your control plane",
        "": "50K per unique tuple, we send 4 unique PDR patterns",
        "pdrLookup": 500000,
        "": "4 PDRs per session",
        "flowMeasure": 2000000,
        "": "there are 2 QERs and 2 entries per QER",
        "appQERLookup": 2000000,
        "": "there is 1 session QER and 2 entries per session QER",
        "sessionQERLookup": 1000000,
        "": "there are 3 FARs",
        "farLookup": 1500000
    },
```

However, I got the following error message :

> ERRO[2022-02-06T15:44:59Z]/pfcpiface/bess.go:606 main.(*bess).processPDR() pdrLookup method failed with resp: error:{code:28 errmsg:"failed to add a new wildcard pattern"}, err: <nil> 
> ERRO[2022-02-06T15:44:59Z]/pfcpiface/bess.go:606 main.(*bess).processPDR() pdrLookup method failed with resp: error:{code:28 errmsg:"failed to add a new wildcard pattern"}, err: <nil> 
> ERRO[2022-02-06T15:44:59Z]/pfcpiface/bess.go:606 main.(*bess).processPDR() pdrLookup method failed with resp: error:{code:28 errmsg:"failed to add a new wildcard pattern"}, err: <nil>

The BESS logs shows :

> I0206 15:45:00.592695 22897 dpdk.cc:72] HASH: memory allocation failed
> I0206 15:45:00.596714 22910 dpdk.cc:72] HASH: memory allocation failed
> I0206 15:45:00.598145 22923 dpdk.cc:72] HASH: memory allocation failed

How can I solve this problem? Can I solve this error just by assigning additional hugepage?

Thanks.

**Comment by pudelkoM** [comment]
This error occurs when there are too many distinct ternary masks in a wildcard table. The current limit is 16, see https://github.com/omec-project/upf-epc/pull/423.

One approach is reducing the this number of distinct masks by re-using the same across multiple fields: 
e.g. instead of using a partial mask on src and dst ports (`0xff00`), prefer an exact match (`0xffff`) or wildcard (`0x0000`).

**Comment by krsna1729** [comment]
@ParkGyuhwan if you are testing with limited number of tuples (ex -simulate create) then yes you will have to add more memory to the bess container run in docker_setup.sh. By default it launches with only 1G per NUMA. So you can bump it up with -m 4096 and make sure that much amount of memory in hugepages is available.
