### ISSUE TITLE
Add GH tokens to ONF bot account to use with GH Actions

### ISSUE THREAD

**Issue by krsna1729** [omec-project/upf#498]
Replace CR_PAT with a token generated in ONF bot account (currently I think it is from my account and about to expire).
https://cs.github.com/omec-project/upf-epc?q=CR_PAT

**Comment by krsna1729** [comment]
https://github.com/omec-project/upf-epc/settings/secrets/actions

**Comment by pudelkoM** [comment]
Done, using `onf-bot` account now

**Comment by krsna1729** [comment]
Please update permissions of the token to be able to push docker images, PR updates etc., that maybe needed by the actions.
