### ISSUE TITLE
protobuf python package and protoc version incompatibility when building docker image

### ISSUE THREAD

**Issue by dmd17** [omec-project/upf#614]
root@upf-0:/opt/bess/bessctl# bessctl run /opt/bess/bessctl/conf/up4
Traceback (most recent call last):
  File "/bin/bessctl", line 51, in <module>
    from pybess.bess import *
  File "/opt/bess/bessctl/../pybess/[bess.py](http://bess.py/)", line 60, in <module>
    from builtin_pb import service_pb2_grpc
  File "/opt/bess/pybess/builtin_pb/service_pb2_[grpc.py](http://grpc.py/)", line 4, in <module>
    import bess_msg_pb2 as bess__msg__pb2
  File "/opt/bess/pybess/builtin_pb/bess_msg_[pb2.py](http://pb2.py/)", line 16, in <module>
    import error_pb2 as error__pb2
  File "/opt/bess/pybess/builtin_pb/error_[pb2.py](http://pb2.py/)", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/[descriptor.py](http://descriptor.py/)", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _[pb2.py](http://pb2.py/) file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

It seems that there is a version mismatch between the protoc used to generate _pb2.py and the protobuf package installed with pip.

The version of protoc in the bess-deps image ghcr.io/omec-project/upf-epc/bess_build is 3.6.1

In the Dockerfile this is the relevant section

FROM python:3.9.12-slim AS bess
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        libgraph-easy-perl \
        iproute2 \
        iptables \
        iputils-ping \
        tcpdump && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir \
        flask \
        grpcio \
        iptools \
        mitogen \
        protobuf \
        psutil \
        pyroute2 \
        scapy && \
    apt-get --purge remove -y \
        gcc
        

I think the assumption here is that the version of protobuf installed by pip will be 3.9.12
However, the actual version installed is 4.21.1

If we pin the version of protobuf to 3.19.0 it works.

**Comment by amarsri28** [comment]
https://github.com/omec-project/upf/commit/c568d437a82009c68d3815aea121b7d7d479be93

this commit fix it.
