### ISSUE TITLE
Patch not able to Merge due to failing background check

### ISSUE THREAD

**Issue by amarsri28** [omec-project/upf#635]
Patches are not able to merge in branch due to failing of background checks.

**Comment by amarsri28** [comment]
@gab-arrobo  pls post your comments and progress here

**Comment by amarsri28** [comment]
@omecproject   pls let us know when this issue will be resolved.

**Comment by manojgop** [comment]
Can the PR [https://github.com/omec-project/upf/pull/602 ](https://github.com/omec-project/upf/pull/602)  be merged after resolving this issue ?

**Comment by gab-arrobo** [comment]
> @gab-arrobo pls post your comments and progress here

Will do!

**Comment by gab-arrobo** [comment]
The issue with the failing Action (pull_request) got temporarily resolved. Please refer to #636. Currently, the checks should work as expected

**Comment by gab-arrobo** [comment]
> Can the PR [https://github.com/omec-project/upf/pull/602 ](https://github.com/omec-project/upf/pull/602) be merged after resolving this issue ?

@amarsri28 feel free to re-open PR #602 if you deem required

**Comment by gab-arrobo** [comment]
> The issue with the failing Action (pull_request) got temporarily resolved. Please refer to #636. Currently, the checks should work as expected

@amarsri28 you can close this issue, the jobs should be working as expected.

**Comment by amarsri28** [comment]
@gab-arrobo   i am observing few failures still in integration test with following errors -

github.com/omec-project/upf-epc/test/integration/providers	[no test files]
FAIL
make: *** [Makefile:84: test-up4-integration-docker] Error 1
Error: No such container: pfcpiface
Error: Process completed with exit code 1.

**Comment by amarsri28** [comment]
for #602  , seems like i dnt have rights to reopen pr so requested administrator

**Comment by gab-arrobo** [comment]
> @gab-arrobo i am observing few failures still in integration test with following errors - https://github.com/omec-project/upf/actions/runs/3235542881/jobs/5300118828
> 
> github.com/omec-project/upf-epc/test/integration/providers [no test files] FAIL make: *** [Makefile:84: test-up4-integration-docker] Error 1 Error: No such container: pfcpiface Error: Process completed with exit code 1.

Do you still see this issue you are reporting? What is your plan to resolve this issue? Please provide updates.

**Comment by gab-arrobo** [comment]
This issue got addressed. Please open issue if you still see it
