### ISSUE TITLE
Add documentation about configuring and deploying the UPF in af_packet and af_xdp modes

### ISSUE THREAD

**Issue by gab-arrobo** [omec-project/upf#689]
Currently, we have documentation on how to deploy the UPF in Simulation and DPDK modes (https://github.com/omec-project/upf/blob/master/docs/INSTALL.md). However, we are missing documentation on how to configure/deploy the UPF in AF_PACKET and AF_XDP modes, which is needed as several have ask in Slack about deploying the UPF in af_xdp mode or UPF in af_packet mode

- [x] Add documentation to deploy the UPF in AF_PACKET mode
- [ ] Add documentation to deploy the UPF in AF_XDP mode: Addressed by #787

**Comment by sureshmarikkannu** [comment]
working on the documentation. we will update the doc based on verification of xdp mode.

**Comment by v0rdych** [comment]
From my perspective the main reason why AF_XDP mode is not working while running by current docs is that these lines in setup.sh script:
`sudo ip netns exec pause ethtool -N "${ifaces[$i]}" flow-type udp4 action 0
sudo ip netns exec pause ethtool -N "${ifaces[$i]}" flow-type tcp4 action 0`
must be changed for something like that for Access interface:
`sudo ip netns exec pause ethtool -N "${ifaces[$i]}" flow-type udp4 dst-port 2152 action 0
sudo ip netns exec pause ethtool -N "${ifaces[$i]}" flow-type udp4 dst-port 8805 action 1
sudo ip netns exec pause ethtool -N "${ifaces[$i]}" flow-type tcp4 action -1`
to make sure that GTP-U traffic 2152 is going to queue 0, where AF_SOCKET is binded.
And PFCP traffic with port 8805 is going to queue 1 (linux kernel in fact) where it will reash docker container with "pfcpiface" binary.

**Comment by gab-arrobo** [comment]
Thanks for your input, @v0rdych. If possible, feel free to make the modifications needed (e.g., update docker_setup.sh, update documentation (https://github.com/omec-project/upf/blob/master/docs/INSTALL.md), etc.) and open a PR. I will be happy to review it.

**Comment by sureshmarikkannu** [comment]
Inprogress

**Comment by gab-arrobo** [comment]
Documentation for `AF_PACKET` mode was added in PR #716... Documentation for deployment in `AF_XDP` mode is still missing.
