### ISSUE TITLE
IPFrag module initialization fails when hugepage is not enabled

### ISSUE THREAD

**Issue by joaoljr** [omec-project/upf#691]
When using AF_PACKET mode without hugepage enabled (PlainPacketPool is created), the PFrag initialization fails at this ip_frag.cc line:
`indirect_pktmbuf_pool = new bess::DpdkPacketPool();`

The upf.json configuration used is below.
  ip_frag_with_eth_mtu: 1518
  max_ip_defrag_flows: 1000

Without frag/defrag enabled, we see outgoing GTP encapsulated packets being dropped after the Bess output queue in some scenarios where the total packet length exceeds the access interface MTU size.

It is not clear if this is an invalid configuration, i.e., frag/defrag indeed depends on DPDK mode, or a bug.

Also, please consider enabling the frag/defrag modules by default. 

Logs attached. Additional details can be found at the slack sdcore-dev thread below:
[https://app.slack.com/client/T095Z193Q/C02TGUWTC93/thread/C02TGUWTC93-1661199350.360879](url)
[upf.log](https://github.com/omec-project/upf/files/11215348/upf.log)

**Comment by gab-arrobo** [comment]
@amarsri28 can you please help debugging/addressing this issue? If so, I can assign it to you. Thanks!

**Comment by gab-arrobo** [comment]
> @gab-arrobo This is not an issue and same has been discussed/resolved earlier for other customers as well. Huge page is required irrespective of any mode i.e. dpdk or af_packet. fragmentation also uses dpdk numa aware memory for best performance. mentioned in Prerequisites as well - https://github.com/omec-project/upf/blob/master/docs/INSTALL.md
> 
> feel free to upgrade documents in case its required.

@joaoljr FYI
