### ISSUE TITLE
Replace IPDB with NDB in UPF

### ISSUE THREAD

**Issue by saltiyazan** [omec-project/upf#735]
IPDB that is used in UPF is deprecated, and obsolete, we should consider replacing it with NDB.

[IPDB module — pyroute2 0.7.3.post2 documentation](https://docs.pyroute2.org/ipdb_toc.html)

It is for example used in [route_control.py](https://github.com/omec-project/upf/blob/master/conf/route_control.py)

**Comment by gab-arrobo** [comment]
@saltiyazan, is this an issue you can help addressing?

**Comment by gab-arrobo** [comment]
@saltiyazan, can you please take a look at #758 and let me know your comments. I currently have it as a draft because I still need to run an E2E test.

**Comment by saltiyazan** [comment]
> @saltiyazan, can you please take a look at #758 and let me know your comments. I currently have it as a draft because I still need to run an E2E test.

Sure @gab-arrobo 
I'll take look during this week.
