### ISSUE TITLE
[Q] 3GPP version and features support of UPF

### ISSUE THREAD

**Issue by s5uishida** [omec-project/upf#824]
Hi,

Please let's me know a bit about 3GPP compatibility of OMEC UPF.

1. Supported 3GPP version
2. Does it support FTUP (F-TEID allocation / release in the UP function is supported by the UP function)?

Best regards,

--Shigeru

**Comment by gruyaume** [comment]
Hello @s5uishida F-TEID allocation is currently not supported in the UPF. I am working on adding this support. 

Reference:
#840

**Comment by gab-arrobo** [comment]
> Hi,
> 
> Please let's me know a bit about 3GPP compatibility of OMEC UPF.
> 
> 1. Supported 3GPP version
Release 15 and some features from release 16
> 2. Does it support FTUP (F-TEID allocation / release in the UP function is supported by the UP function)?
Yes as part of #840 
>
